name: Deploy NestJS App to Lightsail

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Create .env file for NestJS
        run: |
          echo DATABASE_URL=${{secrets.DATABASE_URL}} >> .env
          echo PORT=${{secrets.PORT}} >> .env
          # echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
          echo REDIS_PASSWORD=${{secrets.REDIS_PASSWORD}} >> .env

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build NestJS app
        run: pnpm run build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 9988 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and Restart Server
        env:
          SERVER_USER: ${{ secrets.SSH_HOST_USER }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          APP_DIR: ${{ secrets.WORK_DIR }}
        run: |
          # 1. 빌드 파일(dist), 패키지 정보, prisma 폴더, .env만 서버로 전송합니다.
          scp -r -P 9988 ./dist ./package.json ./pnpm-lock.yaml ./prisma ./.env $SERVER_USER@$SERVER_IP:$APP_DIR/
          
          # 2. 서버에 접속해서 pnpm 설치 -> 패키지 설치 -> Prisma 생성 -> pm2 재시작
          ssh -p 9988 $SERVER_USER@$SERVER_IP "cd $APP_DIR && npm install -g pnpm && pnpm install --prod && npx prisma generate && pm2 restart plma-backend || pm2 start dist/main.js --name plma-backend"