name: Deploy NestJS to Lightsail

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies & Build
        run: |
          pnpm install
          npx prisma generate
          pnpm run build

      - name: Create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 9988 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer Files to Server
        env:
          SERVER_USER: ${{ secrets.SSH_HOST_USER }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          APP_DIR: "/home/ubuntu/Server/plma_backend_using_nestjs"
        run: |
          # rsync 실행 시 SSH 키를 명시적으로 사용하도록 설정
          rsync -avz -e "ssh -p 9988 -o StrictHostKeyChecking=no" \
            ./dist ./package.json ./pnpm-lock.yaml ./prisma ./.env \
            $SERVER_USER@$SERVER_IP:$APP_DIR/

      - name: Execute on Server
        env:
          SERVER_USER: ${{ secrets.SSH_HOST_USER }}
          SERVER_IP: ${{ secrets.SSH_HOST }}
          APP_DIR: "/home/ubuntu/Server/plma_backend_using_nestjs"
        run: |
          ssh -p 9988 $SERVER_USER@$SERVER_IP "
            export PATH=/home/ubuntu/.nvm/versions/node/v22.15.0/bin:\$PATH
            cd $APP_DIR
            pnpm install --prod
            npx prisma generate
            pm2 restart plma-backend || pm2 start dist/main.js --name plma-backend
          "